// <auto-generated />
using System;
using FitnessTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408195210_AddIsAdminToUser")]
    partial class AddIsAdminToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FitnessTracker.Models.DailyLog", b =>
                {
                    b.Property<int>("Log_ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Log_Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Log_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("DailyLogs");

                    b.HasData(
                        new
                        {
                            Log_ID = 6,
                            Log_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 6,
                            Weight = 94.50m
                        },
                        new
                        {
                            Log_ID = 7,
                            Log_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 7,
                            Weight = 55.20m
                        },
                        new
                        {
                            Log_ID = 8,
                            Log_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 8,
                            Weight = 84.00m
                        },
                        new
                        {
                            Log_ID = 9,
                            Log_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 9,
                            Weight = 69.80m
                        },
                        new
                        {
                            Log_ID = 10,
                            Log_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 10,
                            Weight = 104.50m
                        },
                        new
                        {
                            Log_ID = 11,
                            Log_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 11,
                            Weight = 63.50m
                        },
                        new
                        {
                            Log_ID = 12,
                            Log_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 12,
                            Weight = 75.50m
                        },
                        new
                        {
                            Log_ID = 13,
                            Log_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 13,
                            Weight = 50.50m
                        },
                        new
                        {
                            Log_ID = 14,
                            Log_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 14,
                            Weight = 89.50m
                        },
                        new
                        {
                            Log_ID = 15,
                            Log_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 15,
                            Weight = 67.50m
                        },
                        new
                        {
                            Log_ID = 16,
                            Log_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 16,
                            Weight = 87.50m
                        },
                        new
                        {
                            Log_ID = 17,
                            Log_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 17,
                            Weight = 71.50m
                        },
                        new
                        {
                            Log_ID = 18,
                            Log_Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 18,
                            Weight = 78.50m
                        },
                        new
                        {
                            Log_ID = 19,
                            Log_Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 19,
                            Weight = 60.00m
                        },
                        new
                        {
                            Log_ID = 20,
                            Log_Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 20,
                            Weight = 109.00m
                        },
                        new
                        {
                            Log_ID = 21,
                            Log_Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 21,
                            Weight = 65.50m
                        },
                        new
                        {
                            Log_ID = 22,
                            Log_Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 22,
                            Weight = 81.50m
                        },
                        new
                        {
                            Log_ID = 23,
                            Log_Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 23,
                            Weight = 62.80m
                        },
                        new
                        {
                            Log_ID = 24,
                            Log_Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 24,
                            Weight = 77.20m
                        },
                        new
                        {
                            Log_ID = 25,
                            Log_Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            User_ID = 25,
                            Weight = 57.80m
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseLog", b =>
                {
                    b.Property<int>("Exercise_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories_Burned")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exercise_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exercise_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Log_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Exercise_ID");

                    b.HasIndex("Log_ID");

                    b.ToTable("ExerciseLogs");

                    b.HasData(
                        new
                        {
                            Exercise_ID = 6,
                            Calories_Burned = 200,
                            Duration = 45,
                            Exercise_Name = "Walking",
                            Exercise_Type = "Cardio",
                            Log_ID = 6
                        },
                        new
                        {
                            Exercise_ID = 7,
                            Calories_Burned = 550,
                            Duration = 60,
                            Exercise_Name = "CrossFit",
                            Exercise_Type = "Strength",
                            Log_ID = 7
                        },
                        new
                        {
                            Exercise_ID = 8,
                            Calories_Burned = 220,
                            Duration = 30,
                            Exercise_Name = "Stationary Bike",
                            Exercise_Type = "Cardio",
                            Log_ID = 8
                        },
                        new
                        {
                            Exercise_ID = 9,
                            Calories_Burned = 150,
                            Duration = 45,
                            Exercise_Name = "Pilates",
                            Exercise_Type = "Flexibility",
                            Log_ID = 9
                        },
                        new
                        {
                            Exercise_ID = 10,
                            Calories_Burned = 300,
                            Duration = 45,
                            Exercise_Name = "Water Aerobics",
                            Exercise_Type = "Cardio",
                            Log_ID = 10
                        },
                        new
                        {
                            Exercise_ID = 11,
                            Calories_Burned = 450,
                            Duration = 50,
                            Exercise_Name = "Kickboxing",
                            Exercise_Type = "Cardio",
                            Log_ID = 11
                        },
                        new
                        {
                            Exercise_ID = 12,
                            Calories_Burned = 600,
                            Duration = 90,
                            Exercise_Name = "Powerlifting",
                            Exercise_Type = "Strength",
                            Log_ID = 12
                        },
                        new
                        {
                            Exercise_ID = 13,
                            Calories_Burned = 80,
                            Duration = 20,
                            Exercise_Name = "Stretching",
                            Exercise_Type = "Flexibility",
                            Log_ID = 13
                        },
                        new
                        {
                            Exercise_ID = 14,
                            Calories_Burned = 350,
                            Duration = 30,
                            Exercise_Name = "Rowing",
                            Exercise_Type = "Cardio",
                            Log_ID = 14
                        },
                        new
                        {
                            Exercise_ID = 15,
                            Calories_Burned = 400,
                            Duration = 60,
                            Exercise_Name = "Zumba",
                            Exercise_Type = "Cardio",
                            Log_ID = 15
                        },
                        new
                        {
                            Exercise_ID = 16,
                            Calories_Burned = 500,
                            Duration = 60,
                            Exercise_Name = "Basketball",
                            Exercise_Type = "Sports",
                            Log_ID = 16
                        },
                        new
                        {
                            Exercise_ID = 17,
                            Calories_Burned = 120,
                            Duration = 45,
                            Exercise_Name = "Yoga",
                            Exercise_Type = "Flexibility",
                            Log_ID = 17
                        },
                        new
                        {
                            Exercise_ID = 18,
                            Calories_Burned = 380,
                            Duration = 40,
                            Exercise_Name = "Jogging",
                            Exercise_Type = "Cardio",
                            Log_ID = 18
                        },
                        new
                        {
                            Exercise_ID = 19,
                            Calories_Burned = 200,
                            Duration = 30,
                            Exercise_Name = "Dancing",
                            Exercise_Type = "Cardio",
                            Log_ID = 19
                        },
                        new
                        {
                            Exercise_ID = 20,
                            Calories_Burned = 100,
                            Duration = 30,
                            Exercise_Name = "Physical Therapy",
                            Exercise_Type = "Recovery",
                            Log_ID = 20
                        },
                        new
                        {
                            Exercise_ID = 21,
                            Calories_Burned = 200,
                            Duration = 15,
                            Exercise_Name = "Jump Rope",
                            Exercise_Type = "Cardio",
                            Log_ID = 21
                        },
                        new
                        {
                            Exercise_ID = 22,
                            Calories_Burned = 350,
                            Duration = 45,
                            Exercise_Name = "Calisthenics",
                            Exercise_Type = "Strength",
                            Log_ID = 22
                        },
                        new
                        {
                            Exercise_ID = 23,
                            Calories_Burned = 250,
                            Duration = 30,
                            Exercise_Name = "Elliptical",
                            Exercise_Type = "Cardio",
                            Log_ID = 23
                        },
                        new
                        {
                            Exercise_ID = 24,
                            Calories_Burned = 300,
                            Duration = 20,
                            Exercise_Name = "Sprinting",
                            Exercise_Type = "HIIT",
                            Log_ID = 24
                        },
                        new
                        {
                            Exercise_ID = 25,
                            Calories_Burned = 110,
                            Duration = 40,
                            Exercise_Name = "Tai Chi",
                            Exercise_Type = "Flexibility",
                            Log_ID = 25
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Goal", b =>
                {
                    b.Property<int>("Goal_ID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Achieved")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Current_Value")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<string>("Goal_Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Start_Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Target_Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Target_Value")
                        .HasColumnType("decimal(6, 2)");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Goal_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Goal_ID = 6,
                            Achieved = false,
                            Current_Value = 94.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 80.00m,
                            User_ID = 6
                        },
                        new
                        {
                            Goal_ID = 7,
                            Achieved = false,
                            Current_Value = 55.2m,
                            Goal_Type = "Muscle Gain",
                            Start_Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 58.00m,
                            User_ID = 7
                        },
                        new
                        {
                            Goal_ID = 8,
                            Achieved = false,
                            Current_Value = 84.0m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 75.00m,
                            User_ID = 8
                        },
                        new
                        {
                            Goal_ID = 9,
                            Achieved = false,
                            Current_Value = 69.8m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 60.00m,
                            User_ID = 9
                        },
                        new
                        {
                            Goal_ID = 10,
                            Achieved = false,
                            Current_Value = 104.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 90.00m,
                            User_ID = 10
                        },
                        new
                        {
                            Goal_ID = 11,
                            Achieved = false,
                            Current_Value = 63.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 62.00m,
                            User_ID = 11
                        },
                        new
                        {
                            Goal_ID = 12,
                            Achieved = false,
                            Current_Value = 75.5m,
                            Goal_Type = "Muscle Gain",
                            Start_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 82.00m,
                            User_ID = 12
                        },
                        new
                        {
                            Goal_ID = 13,
                            Achieved = false,
                            Current_Value = 50.5m,
                            Goal_Type = "Weight Gain",
                            Start_Date = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 55.00m,
                            User_ID = 13
                        },
                        new
                        {
                            Goal_ID = 14,
                            Achieved = false,
                            Current_Value = 89.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 80.00m,
                            User_ID = 14
                        },
                        new
                        {
                            Goal_ID = 15,
                            Achieved = false,
                            Current_Value = 67.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 60.00m,
                            User_ID = 15
                        },
                        new
                        {
                            Goal_ID = 16,
                            Achieved = false,
                            Current_Value = 87.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 85.00m,
                            User_ID = 16
                        },
                        new
                        {
                            Goal_ID = 17,
                            Achieved = false,
                            Current_Value = 71.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 60.00m,
                            User_ID = 17
                        },
                        new
                        {
                            Goal_ID = 18,
                            Achieved = false,
                            Current_Value = 78.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 75.00m,
                            User_ID = 18
                        },
                        new
                        {
                            Goal_ID = 19,
                            Achieved = true,
                            Current_Value = 60.0m,
                            Goal_Type = "Maintain Weight",
                            Start_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 60.00m,
                            User_ID = 19
                        },
                        new
                        {
                            Goal_ID = 20,
                            Achieved = false,
                            Current_Value = 109.0m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 95.00m,
                            User_ID = 20
                        },
                        new
                        {
                            Goal_ID = 21,
                            Achieved = false,
                            Current_Value = 65.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 60.00m,
                            User_ID = 21
                        },
                        new
                        {
                            Goal_ID = 22,
                            Achieved = false,
                            Current_Value = 81.5m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 78.00m,
                            User_ID = 22
                        },
                        new
                        {
                            Goal_ID = 23,
                            Achieved = false,
                            Current_Value = 62.8m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 60.00m,
                            User_ID = 23
                        },
                        new
                        {
                            Goal_ID = 24,
                            Achieved = false,
                            Current_Value = 77.2m,
                            Goal_Type = "Muscle Gain",
                            Start_Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 85.00m,
                            User_ID = 24
                        },
                        new
                        {
                            Goal_ID = 25,
                            Achieved = false,
                            Current_Value = 57.8m,
                            Goal_Type = "Weight Loss",
                            Start_Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Date = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Target_Value = 55.00m,
                            User_ID = 25
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.HealthMetric", b =>
                {
                    b.Property<int>("Metric_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Blood_Pressure")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Blood_Sugar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Heart_Rate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Metric_Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Total_Water")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Metric_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("HealthMetrics");

                    b.HasData(
                        new
                        {
                            Metric_ID = 6,
                            Blood_Pressure = "140/90",
                            Blood_Sugar = 110,
                            Heart_Rate = 85,
                            Metric_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1500,
                            User_ID = 6
                        },
                        new
                        {
                            Metric_ID = 7,
                            Blood_Pressure = "110/70",
                            Blood_Sugar = 90,
                            Heart_Rate = 65,
                            Metric_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 3500,
                            User_ID = 7
                        },
                        new
                        {
                            Metric_ID = 8,
                            Blood_Pressure = "130/85",
                            Blood_Sugar = 140,
                            Heart_Rate = 78,
                            Metric_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2000,
                            User_ID = 8
                        },
                        new
                        {
                            Metric_ID = 9,
                            Blood_Pressure = "118/75",
                            Blood_Sugar = 95,
                            Heart_Rate = 82,
                            Metric_Date = new DateTime(2026, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1800,
                            User_ID = 9
                        },
                        new
                        {
                            Metric_ID = 10,
                            Blood_Pressure = "145/95",
                            Blood_Sugar = 105,
                            Heart_Rate = 88,
                            Metric_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1200,
                            User_ID = 10
                        },
                        new
                        {
                            Metric_ID = 11,
                            Blood_Pressure = "115/75",
                            Blood_Sugar = 88,
                            Heart_Rate = 70,
                            Metric_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2500,
                            User_ID = 11
                        },
                        new
                        {
                            Metric_ID = 12,
                            Blood_Pressure = "120/80",
                            Blood_Sugar = 92,
                            Heart_Rate = 60,
                            Metric_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 4000,
                            User_ID = 12
                        },
                        new
                        {
                            Metric_ID = 13,
                            Blood_Pressure = "100/65",
                            Blood_Sugar = 85,
                            Heart_Rate = 90,
                            Metric_Date = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1600,
                            User_ID = 13
                        },
                        new
                        {
                            Metric_ID = 14,
                            Blood_Pressure = "125/82",
                            Blood_Sugar = 98,
                            Heart_Rate = 75,
                            Metric_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2200,
                            User_ID = 14
                        },
                        new
                        {
                            Metric_ID = 15,
                            Blood_Pressure = "112/72",
                            Blood_Sugar = 90,
                            Heart_Rate = 77,
                            Metric_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1900,
                            User_ID = 15
                        },
                        new
                        {
                            Metric_ID = 16,
                            Blood_Pressure = "122/80",
                            Blood_Sugar = 95,
                            Heart_Rate = 68,
                            Metric_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2800,
                            User_ID = 16
                        },
                        new
                        {
                            Metric_ID = 17,
                            Blood_Pressure = "119/78",
                            Blood_Sugar = 89,
                            Heart_Rate = 80,
                            Metric_Date = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1700,
                            User_ID = 17
                        },
                        new
                        {
                            Metric_ID = 18,
                            Blood_Pressure = "128/84",
                            Blood_Sugar = 96,
                            Heart_Rate = 85,
                            Metric_Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2100,
                            User_ID = 18
                        },
                        new
                        {
                            Metric_ID = 19,
                            Blood_Pressure = "115/75",
                            Blood_Sugar = 88,
                            Heart_Rate = 72,
                            Metric_Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2300,
                            User_ID = 19
                        },
                        new
                        {
                            Metric_ID = 20,
                            Blood_Pressure = "135/88",
                            Blood_Sugar = 102,
                            Heart_Rate = 92,
                            Metric_Date = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1400,
                            User_ID = 20
                        },
                        new
                        {
                            Metric_ID = 21,
                            Blood_Pressure = "118/76",
                            Blood_Sugar = 91,
                            Heart_Rate = 76,
                            Metric_Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2000,
                            User_ID = 21
                        },
                        new
                        {
                            Metric_ID = 22,
                            Blood_Pressure = "120/79",
                            Blood_Sugar = 94,
                            Heart_Rate = 66,
                            Metric_Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 2600,
                            User_ID = 22
                        },
                        new
                        {
                            Metric_ID = 23,
                            Blood_Pressure = "114/74",
                            Blood_Sugar = 87,
                            Heart_Rate = 74,
                            Metric_Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1800,
                            User_ID = 23
                        },
                        new
                        {
                            Metric_ID = 24,
                            Blood_Pressure = "115/75",
                            Blood_Sugar = 93,
                            Heart_Rate = 62,
                            Metric_Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 3000,
                            User_ID = 24
                        },
                        new
                        {
                            Metric_ID = 25,
                            Blood_Pressure = "116/77",
                            Blood_Sugar = 89,
                            Heart_Rate = 79,
                            Metric_Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_Water = 1900,
                            User_ID = 25
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.Meal", b =>
                {
                    b.Property<int>("Meal_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Log_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meal_Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Meal_Type")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Meal_ID");

                    b.HasIndex("Log_ID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Meal_ID = 6,
                            Log_ID = 6,
                            Meal_Name = "Lunch",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 7,
                            Log_ID = 7,
                            Meal_Name = "Post-Workout",
                            Meal_Type = "Snack"
                        },
                        new
                        {
                            Meal_ID = 8,
                            Log_ID = 8,
                            Meal_Name = "Dinner",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 9,
                            Log_ID = 9,
                            Meal_Name = "Breakfast",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 10,
                            Log_ID = 10,
                            Meal_Name = "Lunch",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 11,
                            Log_ID = 11,
                            Meal_Name = "Dinner",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 12,
                            Log_ID = 12,
                            Meal_Name = "Pre-Workout",
                            Meal_Type = "Snack"
                        },
                        new
                        {
                            Meal_ID = 13,
                            Log_ID = 13,
                            Meal_Name = "Breakfast",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 14,
                            Log_ID = 14,
                            Meal_Name = "Lunch",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 15,
                            Log_ID = 15,
                            Meal_Name = "Snack",
                            Meal_Type = "Snack"
                        },
                        new
                        {
                            Meal_ID = 16,
                            Log_ID = 16,
                            Meal_Name = "Dinner",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 17,
                            Log_ID = 17,
                            Meal_Name = "Breakfast",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 18,
                            Log_ID = 18,
                            Meal_Name = "Lunch",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 19,
                            Log_ID = 19,
                            Meal_Name = "Dinner",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 20,
                            Log_ID = 20,
                            Meal_Name = "Lunch",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 21,
                            Log_ID = 21,
                            Meal_Name = "Breakfast",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 22,
                            Log_ID = 22,
                            Meal_Name = "Post-Workout",
                            Meal_Type = "Snack"
                        },
                        new
                        {
                            Meal_ID = 23,
                            Log_ID = 23,
                            Meal_Name = "Dinner",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 24,
                            Log_ID = 24,
                            Meal_Name = "Lunch",
                            Meal_Type = "Main"
                        },
                        new
                        {
                            Meal_ID = 25,
                            Log_ID = 25,
                            Meal_Name = "Snack",
                            Meal_Type = "Snack"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.MealItem", b =>
                {
                    b.Property<int>("Meal_Item_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Carbs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Fat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Food_Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Meal_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Protein")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Meal_Item_ID");

                    b.HasIndex("Meal_ID");

                    b.ToTable("MealItems");

                    b.HasData(
                        new
                        {
                            Meal_Item_ID = 6,
                            Calories = 350,
                            Carbs = 0,
                            Fat = 20,
                            Food_Name = "Grilled Salmon",
                            Meal_ID = 6,
                            Protein = 40,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 7,
                            Calories = 180,
                            Carbs = 5,
                            Fat = 2,
                            Food_Name = "Protein Shake",
                            Meal_ID = 7,
                            Protein = 30,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 8,
                            Calories = 450,
                            Carbs = 0,
                            Fat = 30,
                            Food_Name = "Steak",
                            Meal_ID = 8,
                            Protein = 45,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 9,
                            Calories = 100,
                            Carbs = 15,
                            Fat = 0,
                            Food_Name = "Greek Yogurt",
                            Meal_ID = 9,
                            Protein = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 10,
                            Calories = 600,
                            Carbs = 5,
                            Fat = 40,
                            Food_Name = "Burger (No Bun)",
                            Meal_ID = 10,
                            Protein = 50,
                            Quantity = 2
                        },
                        new
                        {
                            Meal_Item_ID = 11,
                            Calories = 300,
                            Carbs = 45,
                            Fat = 8,
                            Food_Name = "Quinoa Bowl",
                            Meal_ID = 11,
                            Protein = 12,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 12,
                            Calories = 210,
                            Carbs = 54,
                            Fat = 0,
                            Food_Name = "Banana",
                            Meal_ID = 12,
                            Protein = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Meal_Item_ID = 13,
                            Calories = 200,
                            Carbs = 3,
                            Fat = 12,
                            Food_Name = "Spinach Omelette",
                            Meal_ID = 13,
                            Protein = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 14,
                            Calories = 220,
                            Carbs = 45,
                            Fat = 2,
                            Food_Name = "Brown Rice",
                            Meal_ID = 14,
                            Protein = 5,
                            Quantity = 200
                        },
                        new
                        {
                            Meal_Item_ID = 15,
                            Calories = 160,
                            Carbs = 6,
                            Fat = 14,
                            Food_Name = "Almonds",
                            Meal_ID = 15,
                            Protein = 6,
                            Quantity = 30
                        },
                        new
                        {
                            Meal_Item_ID = 16,
                            Calories = 165,
                            Carbs = 0,
                            Fat = 4,
                            Food_Name = "Chicken Breast",
                            Meal_ID = 16,
                            Protein = 31,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 17,
                            Calories = 250,
                            Carbs = 20,
                            Fat = 15,
                            Food_Name = "Avocado Toast",
                            Meal_ID = 17,
                            Protein = 5,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 18,
                            Calories = 300,
                            Carbs = 60,
                            Fat = 2,
                            Food_Name = "Pasta",
                            Meal_ID = 18,
                            Protein = 10,
                            Quantity = 150
                        },
                        new
                        {
                            Meal_Item_ID = 19,
                            Calories = 220,
                            Carbs = 15,
                            Fat = 12,
                            Food_Name = "Tofu Stir Fry",
                            Meal_ID = 19,
                            Protein = 18,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 20,
                            Calories = 500,
                            Carbs = 20,
                            Fat = 35,
                            Food_Name = "Fried Chicken",
                            Meal_ID = 20,
                            Protein = 25,
                            Quantity = 2
                        },
                        new
                        {
                            Meal_Item_ID = 21,
                            Calories = 350,
                            Carbs = 50,
                            Fat = 10,
                            Food_Name = "Pancakes",
                            Meal_ID = 21,
                            Protein = 8,
                            Quantity = 2
                        },
                        new
                        {
                            Meal_Item_ID = 22,
                            Calories = 120,
                            Carbs = 6,
                            Fat = 2,
                            Food_Name = "Cottage Cheese",
                            Meal_ID = 22,
                            Protein = 14,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 23,
                            Calories = 180,
                            Carbs = 30,
                            Fat = 1,
                            Food_Name = "Lentil Soup",
                            Meal_ID = 23,
                            Protein = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 24,
                            Calories = 110,
                            Carbs = 26,
                            Fat = 0,
                            Food_Name = "Sweet Potato",
                            Meal_ID = 24,
                            Protein = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Meal_Item_ID = 25,
                            Calories = 110,
                            Carbs = 12,
                            Fat = 7,
                            Food_Name = "Dark Chocolate",
                            Meal_ID = 25,
                            Protein = 1,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("User_ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_ID = 6,
                            Email = "ahmed@mail.com",
                            IsAdmin = false,
                            Password = "pwd123",
                            User_Name = "Ahmed"
                        },
                        new
                        {
                            User_ID = 7,
                            Email = "mona@mail.com",
                            IsAdmin = true,
                            Password = "m0n@!",
                            User_Name = "Mona"
                        },
                        new
                        {
                            User_ID = 8,
                            Email = "omar@mail.com",
                            IsAdmin = true,
                            Password = "omr99",
                            User_Name = "Omar"
                        },
                        new
                        {
                            User_ID = 9,
                            Email = "laila@mail.com",
                            IsAdmin = false,
                            Password = "lolo22",
                            User_Name = "Laila"
                        },
                        new
                        {
                            User_ID = 10,
                            Email = "tarek@mail.com",
                            IsAdmin = true,
                            Password = "tk_88",
                            User_Name = "Tarek"
                        },
                        new
                        {
                            User_ID = 11,
                            Email = "salma@mail.com",
                            IsAdmin = false,
                            Password = "s@lm@1",
                            User_Name = "Salma"
                        },
                        new
                        {
                            User_ID = 12,
                            Email = "youssef@mail.com",
                            IsAdmin = false,
                            Password = "jo1234",
                            User_Name = "Youssef"
                        },
                        new
                        {
                            User_ID = 13,
                            Email = "hoda@mail.com",
                            IsAdmin = false,
                            Password = "hoda77",
                            User_Name = "Hoda"
                        },
                        new
                        {
                            User_ID = 14,
                            Email = "mahmoud@mail.com",
                            IsAdmin = false,
                            Password = "mah_00",
                            User_Name = "Mahmoud"
                        },
                        new
                        {
                            User_ID = 15,
                            Email = "farah@mail.com",
                            IsAdmin = false,
                            Password = "farah#",
                            User_Name = "Farah"
                        },
                        new
                        {
                            User_ID = 16,
                            Email = "khaled@mail.com",
                            IsAdmin = false,
                            Password = "kh_991",
                            User_Name = "Khaled"
                        },
                        new
                        {
                            User_ID = 17,
                            Email = "rania@mail.com",
                            IsAdmin = false,
                            Password = "r@nia",
                            User_Name = "Rania"
                        },
                        new
                        {
                            User_ID = 18,
                            Email = "ziad@mail.com",
                            IsAdmin = false,
                            Password = "zizou!",
                            User_Name = "Ziad"
                        },
                        new
                        {
                            User_ID = 19,
                            Email = "dina@mail.com",
                            IsAdmin = false,
                            Password = "dina_d",
                            User_Name = "Dina"
                        },
                        new
                        {
                            User_ID = 20,
                            Email = "ali@mail.com",
                            IsAdmin = false,
                            Password = "ali2026",
                            User_Name = "Ali"
                        },
                        new
                        {
                            User_ID = 21,
                            Email = "nada@mail.com",
                            IsAdmin = false,
                            Password = "nada*8",
                            User_Name = "Nada"
                        },
                        new
                        {
                            User_ID = 22,
                            Email = "rami@mail.com",
                            IsAdmin = false,
                            Password = "rami_r",
                            User_Name = "Rami"
                        },
                        new
                        {
                            User_ID = 23,
                            Email = "yasmine2@mail.com",
                            IsAdmin = false,
                            Password = "yas22",
                            User_Name = "Yasmine"
                        },
                        new
                        {
                            User_ID = 24,
                            Email = "kareem@mail.com",
                            IsAdmin = false,
                            Password = "kimo88",
                            User_Name = "Kareem"
                        },
                        new
                        {
                            User_ID = 25,
                            Email = "merna@mail.com",
                            IsAdmin = false,
                            Password = "merna1",
                            User_Name = "Merna"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.UserProfile", b =>
                {
                    b.Property<int>("Profile_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Activity_Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Medical_Condition")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Target_Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("User_ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Profile_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Profile_ID = 6,
                            Activity_Level = "Sedentary",
                            Date_of_Birth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 180.00m,
                            Medical_Condition = "Hypertension",
                            Target_Weight = 80.00m,
                            User_ID = 6,
                            Weight = 95.00m
                        },
                        new
                        {
                            Profile_ID = 7,
                            Activity_Level = "Very Active",
                            Date_of_Birth = new DateTime(1995, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 165.00m,
                            Target_Weight = 58.00m,
                            User_ID = 7,
                            Weight = 55.00m
                        },
                        new
                        {
                            Profile_ID = 8,
                            Activity_Level = "Light",
                            Date_of_Birth = new DateTime(1988, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 172.00m,
                            Medical_Condition = "Type 2 Diabetes",
                            Target_Weight = 75.00m,
                            User_ID = 8,
                            Weight = 85.00m
                        },
                        new
                        {
                            Profile_ID = 9,
                            Activity_Level = "Moderate",
                            Date_of_Birth = new DateTime(2000, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 155.00m,
                            Medical_Condition = "PCOS",
                            Target_Weight = 60.00m,
                            User_ID = 9,
                            Weight = 70.00m
                        },
                        new
                        {
                            Profile_ID = 10,
                            Activity_Level = "Low",
                            Date_of_Birth = new DateTime(1985, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 185.00m,
                            Medical_Condition = "High Cholesterol",
                            Target_Weight = 90.00m,
                            User_ID = 10,
                            Weight = 105.00m
                        },
                        new
                        {
                            Profile_ID = 11,
                            Activity_Level = "Active",
                            Date_of_Birth = new DateTime(1998, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 168.00m,
                            Target_Weight = 62.00m,
                            User_ID = 11,
                            Weight = 64.00m
                        },
                        new
                        {
                            Profile_ID = 12,
                            Activity_Level = "Very Active",
                            Date_of_Birth = new DateTime(2001, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 178.00m,
                            Target_Weight = 82.00m,
                            User_ID = 12,
                            Weight = 75.00m
                        },
                        new
                        {
                            Profile_ID = 13,
                            Activity_Level = "Light",
                            Date_of_Birth = new DateTime(1992, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 160.00m,
                            Medical_Condition = "Anemia",
                            Target_Weight = 55.00m,
                            User_ID = 13,
                            Weight = 50.00m
                        },
                        new
                        {
                            Profile_ID = 14,
                            Activity_Level = "Moderate",
                            Date_of_Birth = new DateTime(1980, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 170.00m,
                            Target_Weight = 80.00m,
                            User_ID = 14,
                            Weight = 90.00m
                        },
                        new
                        {
                            Profile_ID = 15,
                            Activity_Level = "Low",
                            Date_of_Birth = new DateTime(1996, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 164.00m,
                            Medical_Condition = "Thyroid Issue",
                            Target_Weight = 60.00m,
                            User_ID = 15,
                            Weight = 68.00m
                        },
                        new
                        {
                            Profile_ID = 16,
                            Activity_Level = "Active",
                            Date_of_Birth = new DateTime(1993, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 182.00m,
                            Target_Weight = 85.00m,
                            User_ID = 16,
                            Weight = 88.00m
                        },
                        new
                        {
                            Profile_ID = 17,
                            Activity_Level = "Sedentary",
                            Date_of_Birth = new DateTime(1987, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 158.00m,
                            Target_Weight = 60.00m,
                            User_ID = 17,
                            Weight = 72.00m
                        },
                        new
                        {
                            Profile_ID = 18,
                            Activity_Level = "Moderate",
                            Date_of_Birth = new DateTime(1999, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 176.00m,
                            Medical_Condition = "Asthma",
                            Target_Weight = 75.00m,
                            User_ID = 18,
                            Weight = 79.00m
                        },
                        new
                        {
                            Profile_ID = 19,
                            Activity_Level = "Active",
                            Date_of_Birth = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 166.00m,
                            Target_Weight = 60.00m,
                            User_ID = 19,
                            Weight = 60.00m
                        },
                        new
                        {
                            Profile_ID = 20,
                            Activity_Level = "Low",
                            Date_of_Birth = new DateTime(1982, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 188.00m,
                            Medical_Condition = "Joint Pain",
                            Target_Weight = 95.00m,
                            User_ID = 20,
                            Weight = 110.00m
                        },
                        new
                        {
                            Profile_ID = 21,
                            Activity_Level = "Moderate",
                            Date_of_Birth = new DateTime(1997, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 162.00m,
                            Target_Weight = 60.00m,
                            User_ID = 21,
                            Weight = 66.00m
                        },
                        new
                        {
                            Profile_ID = 22,
                            Activity_Level = "Active",
                            Date_of_Birth = new DateTime(1994, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 174.00m,
                            Target_Weight = 78.00m,
                            User_ID = 22,
                            Weight = 82.00m
                        },
                        new
                        {
                            Profile_ID = 23,
                            Activity_Level = "Light",
                            Date_of_Birth = new DateTime(1989, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 167.00m,
                            Target_Weight = 60.00m,
                            User_ID = 23,
                            Weight = 63.00m
                        },
                        new
                        {
                            Profile_ID = 24,
                            Activity_Level = "Very Active",
                            Date_of_Birth = new DateTime(2000, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Height = 180.00m,
                            Target_Weight = 85.00m,
                            User_ID = 24,
                            Weight = 77.00m
                        },
                        new
                        {
                            Profile_ID = 25,
                            Activity_Level = "Moderate",
                            Date_of_Birth = new DateTime(1991, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            Height = 159.00m,
                            Target_Weight = 55.00m,
                            User_ID = 25,
                            Weight = 58.00m
                        });
                });

            modelBuilder.Entity("FitnessTracker.Models.DailyLog", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.ExerciseLog", b =>
                {
                    b.HasOne("FitnessTracker.Models.DailyLog", "DailyLog")
                        .WithMany("Exercises")
                        .HasForeignKey("Log_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("FitnessTracker.Models.Goal", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.HealthMetric", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithMany("HealthMetrics")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.Meal", b =>
                {
                    b.HasOne("FitnessTracker.Models.DailyLog", "DailyLog")
                        .WithMany("Meals")
                        .HasForeignKey("Log_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("FitnessTracker.Models.MealItem", b =>
                {
                    b.HasOne("FitnessTracker.Models.Meal", "Meal")
                        .WithMany("MealItems")
                        .HasForeignKey("Meal_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FitnessTracker.Models.UserProfile", b =>
                {
                    b.HasOne("FitnessTracker.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FitnessTracker.Models.UserProfile", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Models.DailyLog", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("FitnessTracker.Models.Meal", b =>
                {
                    b.Navigation("MealItems");
                });

            modelBuilder.Entity("FitnessTracker.Models.User", b =>
                {
                    b.Navigation("DailyLogs");

                    b.Navigation("Goals");

                    b.Navigation("HealthMetrics");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
